<a href="https://colab.research.google.com/github/Anu4477/Data-science/blob/main/15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# json file import from github
import pandas as pd
url="https://raw.githubusercontent.com/Anu4477/Data-science/main/file2.json"
df= pd.read_json(url)
#head ->starting 5 rows
print(df.head())
df
#head -> 2 rows data
#print(df.head(-2))

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

In [ ]:
#tail
# json file import from github
import pandas as pd
url="https://raw.githubusercontent.com/Anu4477/Data-science/main/file2.json"
df= pd.read_json(url)
print(df.head(2))
print(df.tail(-1))
df

      name  roll no  marks
0  dheeraj      123     10
1    kunal     1234     20
       name  roll no  marks
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

In [ ]:
import pandas as pd
url="https://raw.githubusercontent.com/Anu4477/Data-science/main/file2.json"
df= pd.read_json(url)
df.shape

(5, 3)

In [ ]:
import pandas as pd
import numpy as np
url="https://raw.githubusercontent.com/Anu4477/Data-science/main/file2.json"
df= pd.read_json(url)
#df["salary"]=[100,200,300,np.nan,500]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     5 non-null      object
 1   roll no  5 non-null      int64
 2   marks    5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [ ]:
import pandas as pd
#url="https://raw.githubusercontent.com/Anu4477/Data-science/main/file2.json"
#df= pd.read_json(url)
df = pd.DataFrame(data=[10,20,30,40,50],columns=["age"])
df.shape
df

   age
0   10
1   20
2   30
3   40
4   50

In [ ]:
import pandas as pd
#url="https://raw.githubusercontent.com/Anu4477/Data-science/main/file2.json"
df= pd.read_json(url)
df.rename(columns={"name":"student_name"},inplace=True)
df

  student_name  roll no  marks
0      dheeraj      123     10
1        kunal     1234     20
2     abhishek    12345     30
3      praveen    12356     40
4       anjali  1234567     50

In [ ]:
import pandas as pd
#url="https://raw.githubusercontent.com/Anu4477/Data-science/main/file2.json"
df= pd.read_json(url)
df.describe()

            roll no      marks
count  5.000000e+00   5.000000
mean   2.521250e+05  30.000000
std    5.492329e+05  15.811388
min    1.230000e+02  10.000000
25%    1.234000e+03  20.000000
50%    1.234500e+04  30.000000
75%    1.235600e+04  40.000000
max    1.234567e+06  50.000000

In [ ]:
#PRACTICE QUESTION
import pandas as pd

data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}

df = pd.DataFrame(data)

print(df)

print("--------------------------------------------")

# Head
print(df.head(3))

print("--------------------------------------------")

# Tail
print(df.tail(3))

print("--------------------------------------------")

# Info
print(df.info())


print("--------------------------------------------")

# Rename Column
df.rename(columns={"Salary": "Monthly_Salary"}, inplace=True)
print(df)

print("--------------------------------------------")

# Shape
print(df.shape)

print("--------------------------------------------")

# Describe
print(df.describe())

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3
--------------------------------------------
   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
--------------------------------------------
   Emp_ID  Name Department  Salary  Experience
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3
--------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Emp_ID      6 non-null      int64
 1   Name        6 non-null      object
 2   Department  6 non-null      object
 3   Salary      6 non-null      int64
 4   Experience  6 non-null      int64
dtypes: int64(3), object(2)
memory usage: 372.0+ bytes
None
--------------------------------------------
   Emp_ID  Name Department  Monthly_Salary  Experience
0     101  Amit         IT           50000           2
1     102  Riya         HR           45000           3
2     103   Raj    Finance           60000           5
3     104  Sara         IT           55000           4
4     105  John      Sales           48000           1
5     106  Neha         HR           52000           3
--------------------------------------------
(6, 5)
--------------------------------------------
           Emp_ID  Monthly_Salary  Experience
count    6.000000        6.000000    6.000000
mean   103.500000    51666.666667    3.000000
std      1.870829     5316.640543    1.414214
min    101.000000    45000.000000    1.000000
25%    102.250000    48500.000000    2.250000
50%    103.500000    51000.000000    3.000000
75%    104.750000    54250.000000    3.750000
max    106.000000    60000.000000    5.000000

OPERATIONS ON COLUMN

In [ ]:
import pandas as pd
url="https://raw.githubusercontent.com/Anu4477/Data-science/main/file2.json"
df= pd.read_json(url)
#get single column
df["name"]
#add single column
df["salary"]=df["marks"]+100
#add single column
df["salary"]=[100,200,300,400,500]
df

       name  roll no  marks  salary
0   dheeraj      123     10     100
1     kunal     1234     20     200
2  abhishek    12345     30     300
3   praveen    12356     40     400
4    anjali  1234567     50     500

In [ ]:
import pandas as pd
d={"name":["Rahul","nikita","pinky"],
      "salary":[10000000,20000000,30000000]}

df= pd.DataFrame(data=d)
#df["marks"]=[10,20,30]
df["marks"]= df["salary"]/2
df["incremenrt"]=df["salary"]+(df["salary"] / 10)
df

     name    salary       marks  incremenrt
0   Rahul  10000000   5000000.0  11000000.0
1  nikita  20000000  10000000.0  22000000.0
2   pinky  30000000  15000000.0  33000000.0