<a href="https://colab.research.google.com/github/Anu4477/Data-science/blob/main/17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**SORTING**
1. Ascending -> by default
2. descending ->false

In [ ]:
#sorting
import pandas as pd
url="https://raw.githubusercontent.com/Anu4477/Data-science/main/studentdata.json"
df = pd.read_json(url)
#by default
#df.sort_values("english")
#in descending
#df.sort_values("english",ascending=False)

#by default ascending method 1
#df.sort_values(by=["english"],ascending=[False])

#multiple column sort
#df.sort_values(by=["english","maths"],ascending=[False,True])

#atoz
df["name"]=df["name"].str.lower()
df.sort_values("name")

       name  gender  physics  maths  english
0      arun    Male       88     87       78
8    dinesh    Male       56     45       67
10    gowri  Female      100    100      100
9      hema  Female       71     90       23
13  jenifer  Female       67     88       90
7   kavitha  Female       78     71       67
2   moorthy    Male       89     90       70
12  murugan    Male       34     89       78
5     priya  Female       56     46       78
3      raja    Male       30     25       40
1    rajesh    Male       96    100       95
11      ram    Male       78     55       47
6    sundar    Male       12     67       67
4      usha  Female       67     45       78

In [ ]:
#add col
import pandas as pd
url="https://raw.githubusercontent.com/Anu4477/Data-science/main/studentdata.json"
df = pd.read_json(url)
df["total"]=df["english"]+df["maths"]+df["physics"]
df
#add row
df.loc[14]=["anushka","Female",80,50,90,220]
df
#delete column
df.drop("total",axis=1)
#delete row
df.drop(14,axis=0)

#delete row and column simultaneously
#df.drop()

       name  gender  physics  maths  english  total
0      arun    Male       88     87       78    253
1    rajesh    Male       96    100       95    291
2   moorthy    Male       89     90       70    249
3      raja    Male       30     25       40     95
4      usha  Female       67     45       78    190
5     priya  Female       56     46       78    180
6    Sundar    Male       12     67       67    146
7   Kavitha  Female       78     71       67    216
8    Dinesh    Male       56     45       67    168
9      Hema  Female       71     90       23    184
10    Gowri  Female      100    100      100    300
11      Ram    Male       78     55       47    180
12  Murugan    Male       34     89       78    201
13  Jenifer  Female       67     88       90    245

In [ ]:
import pandas as pd
url="https://raw.githubusercontent.com/Anu4477/Data-science/main/studentdata.json"
df = pd.read_json(url)
df
df['doj']=['2025-01-01','2025-01-02','2025-01-03','2025-01-04','2025-01-05','2025-01-06','2025-01-07','2025-01-08','2025-01-09','2025-01-10','2025-01-11','2025-01-12','2025-01-13','2025-01-14']
df

       name  gender  physics  maths  english         doj
0      arun    Male       88     87       78  2025-01-01
1    rajesh    Male       96    100       95  2025-01-02
2   moorthy    Male       89     90       70  2025-01-03
3      raja    Male       30     25       40  2025-01-04
4      usha  Female       67     45       78  2025-01-05
5     priya  Female       56     46       78  2025-01-06
6    Sundar    Male       12     67       67  2025-01-07
7   Kavitha  Female       78     71       67  2025-01-08
8    Dinesh    Male       56     45       67  2025-01-09
9      Hema  Female       71     90       23  2025-01-10
10    Gowri  Female      100    100      100  2025-01-11
11      Ram    Male       78     55       47  2025-01-12
12  Murugan    Male       34     89       78  2025-01-13
13  Jenifer  Female       67     88       90  2025-01-14

In [ ]:
import pandas as pd
url="https://raw.githubusercontent.com/Anu4477/Data-science/main/file2.json"
df = pd.read_json(url)
df['doj']=['2025-01-01','2025-01-02','2025-01-03','2025-01-04','2025-01-05']
df

#convert string to date
df['doj']=pd.to_datetime(df['doj'])
df['doj'].dtypes

#date operation
df['doj'].dt.year
df['doj'].dt.month
df['doj'].dt.day
df['doj'].dt.day_name()

#20 days
df['doj']+pd.to_timedelta(20,unit='D')

0   2025-01-21
1   2025-01-22
2   2025-01-23
3   2025-01-24
4   2025-01-25
Name: doj, dtype: datetime64[ns]